modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Cobblemon Multiplatform-NeoForge Template Sidemod"
authors = "Me!"
description = '''
A very cool multi-line description!
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
